const palabrasKatakanas = [ 
    { katakana: 'アフリカ', lectura: 'afurika', significado: 'África' },
    { katakana: 'アメリカ', lectura: 'amerika', significado: 'América' },
    { katakana: 'イギリス', lectura: 'igirisu', significado: 'Inglaterra' },
    { katakana: 'イタリア', lectura: 'itaria', significado: 'Italia' },
    { katakana: 'インド', lectura: 'indo', significado: 'India' },
    { katakana: 'オーストラリア', lectura: 'oosutoraria', significado: 'Australia' },
    { katakana: 'カナダ', lectura: 'kanada', significado: 'Canadá' },
    { katakana: 'フランス', lectura: 'furansu', significado: 'Francia' },
    { katakana: 'ドイツ', lectura: 'doitsu', significado: 'Alemania' },
    { katakana: 'ロシア', lectura: 'roshia', significado: 'Rusia' },
    
    { katakana: 'ホテル', lectura: 'hoteru', significado: 'hotel' },
    { katakana: 'レストラン', lectura: 'resutoran', significado: 'restaurante' },
    { katakana: 'スーパー', lectura: 'suupaa', significado: 'supermercado' },
    { katakana: 'デパート', lectura: 'depaato', significado: 'tienda por departamentos' },
    { katakana: 'コンビニ', lectura: 'konbini', significado: 'tienda de conveniencia' },
    { katakana: 'ガソリンスタンド', lectura: 'gasorin sutando', significado: 'gasolinera' },
    { katakana: 'エレベーター', lectura: 'erebeetaa', significado: 'ascensor' },
    { katakana: 'エスカレーター', lectura: 'esukareetaa', significado: 'escalera mecánica' },
    { katakana: 'トイレ', lectura: 'toire', significado: 'baño' },
    { katakana: 'バス', lectura: 'basu', significado: 'autobús' },

    { katakana: 'タクシー', lectura: 'takushii', significado: 'taxi' },
    { katakana: 'バイク', lectura: 'baiku', significado: 'motocicleta' },
    { katakana: 'パトカー', lectura: 'patokaa', significado: 'coche patrulla' },
    { katakana: 'スポーツ', lectura: 'supootsu', significado: 'deporte' },
    { katakana: 'テニス', lectura: 'tenisu', significado: 'tenis' },
    { katakana: 'サッカー', lectura: 'sakkaa', significado: 'fútbol' },
    { katakana: 'バスケットボール', lectura: 'basukettobooru', significado: 'baloncesto' },
    { katakana: 'ゴルフ', lectura: 'gorufu', significado: 'golf' },
    { katakana: 'ラジオ', lectura: 'rajio', significado: 'radio' },
    { katakana: 'テレビ', lectura: 'terebi', significado: 'televisión' },

    { katakana: 'カメラ', lectura: 'kamera', significado: 'cámara' },
    { katakana: 'コンピューター', lectura: 'konpyuutaa', significado: 'computadora' },
    { katakana: 'パソコン', lectura: 'pasokon', significado: 'ordenador personal' },
    { katakana: 'インターネット', lectura: 'intaanetto', significado: 'internet' },
    { katakana: 'スマートフォン', lectura: 'sumaatofon', significado: 'teléfono inteligente' },
    { katakana: 'タブレット', lectura: 'taburetto', significado: 'tablet' },
    { katakana: 'メール', lectura: 'meeru', significado: 'correo electrónico' },
    { katakana: 'ゲーム', lectura: 'geemu', significado: 'videojuego' },
    { katakana: 'アニメ', lectura: 'anime', significado: 'animación japonesa' },
    { katakana: 'マンガ', lectura: 'manga', significado: 'historieta japonesa' },

    { katakana: 'コーヒー', lectura: 'koohī', significado: 'café' },
    { katakana: 'ジュース', lectura: 'juusu', significado: 'jugo' },
    { katakana: 'ビール', lectura: 'biiru', significado: 'cerveza' },
    { katakana: 'ワイン', lectura: 'wain', significado: 'vino' },
    { katakana: 'チョコレート', lectura: 'chokoreeto', significado: 'chocolate' },
    { katakana: 'アイスクリーム', lectura: 'aisukuriimu', significado: 'helado' },
    { katakana: 'サンドイッチ', lectura: 'sandoicchi', significado: 'sándwich' },
    { katakana: 'ハンバーガー', lectura: 'hanbaagaa', significado: 'hamburguesa' },
    { katakana: 'ピザ', lectura: 'piza', significado: 'pizza' },
    { katakana: 'パスタ', lectura: 'pasuta', significado: 'pasta' },

    { katakana: 'ネクタイ', lectura: 'nekutai', significado: 'corbata' },
    { katakana: 'シャツ', lectura: 'shatsu', significado: 'camisa' },
    { katakana: 'スカート', lectura: 'sukaato', significado: 'falda' },
    { katakana: 'ジャケット', lectura: 'jaketto', significado: 'chaqueta' },
    { katakana: 'コート', lectura: 'kooto', significado: 'abrigo' },
    { katakana: 'バッグ', lectura: 'baggu', significado: 'bolso' },
    { katakana: 'スーツ', lectura: 'suutsu', significado: 'traje' },
    { katakana: 'メガネ', lectura: 'megane', significado: 'gafas' },
    { katakana: 'アクセサリー', lectura: 'akusesarii', significado: 'accesorios' },
    { katakana: 'ウィンドウショッピング', lectura: 'uindoo shoppingu', significado: 'ver escaparates' },

    { katakana: 'デート', lectura: 'deeto', significado: 'cita romántica' },
    { katakana: 'パーティー', lectura: 'paatii', significado: 'fiesta' },
    { katakana: 'ニュース', lectura: 'nyuusu', significado: 'noticias' },
    { katakana: 'ビデオ', lectura: 'bideo', significado: 'video' },
    { katakana: 'アルバイト', lectura: 'arubaito', significado: 'trabajo a tiempo parcial' },
    { katakana: 'サラリーマン', lectura: 'sarariiman', significado: 'asalariado' },
    { katakana: 'ボーナス', lectura: 'boonasu', significado: 'bono' },
    { katakana: 'エネルギー', lectura: 'enerugii', significado: 'energía' },
    { katakana: 'プール', lectura: 'puuru', significado: 'piscina' },
    { katakana: 'リモコン', lectura: 'rimokon', significado: 'control remoto' }
];
